version: '3.3'
services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: 'demo'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mandico'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'P@ssw0rd1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd1234'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'