version: '3.3'
services:
  db:
    image: postgres:15
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_DB: 'demo'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'mandico'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'P@ssw0rd1234'
      # Password for root access
      POSTGRES_PASSWORD: 'P@ssw0rd1234'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080