apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-front
  template:
    metadata:
      labels:
        app: go-front
    spec:
      containers:
      - name: go-front
        image: luizmandico/go-front:1.0.0
        env:
          - name: APP_VERSION
            value: 3.2.1
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 8888